name: libela_practition
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  equatable: ^2.0.5
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  infinite_scroll_pagination: ^4.0.0
  pull_to_refresh: ^2.0.0
  cloud_firestore: ^4.15.5
  dio: ^5.4.1
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.3.0
  logger: ^2.0.2+1
  get_it: ^7.6.7
  calendar_date_picker2: ^0.5.3
  injectable: ^2.3.2
  fpdart: ^1.1.0
  file_picker: ^6.1.1
  pdf_thumbnail: ^0.1.6+1
  pdfx: ^2.6.0
  fl_chart: ^0.66.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 20
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/svg/
    - assets/images/
    - assets/env/
    - assets/json/
    - assets/icon/
  uses-material-design: true

